# site settings
title: Scorched
subtitle: Carbon
email: youremailaddress@gmail.com
description: Carbon Forged By Fire
baseurl: '' # the subpath of your site, e.g. /blog
url: https://scorchedcarbon.github.io # the base hostname & protocol for your site
author:
street_address: 1234 Somewhere Road
city: Nashville
state: TN
zip_code: 55555
country: United States of America
phone: (716) 555-5555

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: 

# build settings
markdown: kramdown
highlighter: pygments

sass:
  style: compressed
